receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:9999
      http:
        endpoint: 127.0.0.1:4318

exporters:
  logging :
    verbosity: detailed
  file: # the File Exporter, to ingest logs to local file
    path: example.json
  prometheus:
    endpoint: 127.0.0.1:9464 # 프로메테우스에서 수집에 사용하는 IP
  
  otlp/jaeger:
    endpoint: 127.0.0.1:4317
    tls :
      insecure : true
  otlphttp:
    endpoint: http://127.0.0.1:3100/otlp

processors:
  batch:
  filter/severity:
    logs:
      log_record:
        - 'severity_number > 10'

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [filter/severity]
      exporters: [file]

    traces:
      receivers: [otlp]
      processors: [filter/severity]
      exporters: [file]

    metrics:
      receivers: [otlp]
      processors: [filter/severity]
      exporters: [file]