receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:9999
      http:
        endpoint: 127.0.0.1:4318

exporters:
  logging :
    verbosity: detailed
  file/original_logs:
    path: data/original_logs.json
  file/filtered_logs:
    path: data/filtered_logs.json
  file/original_span:
    path: data/original_span.json
  file/filtered_span:
    path: data/filtered_span.json

  file/test:
    path: data/test.json

  prometheus:
    endpoint: 127.0.0.1:9464 # 프로메테우스에서 수집에 사용하는 IP

  file/metrics:
    path: data/metrics.json

  otlp/jaeger:
    endpoint: 127.0.0.1:4317
    tls :
      insecure : true
  otlphttp:
    endpoint: http://127.0.0.1:3100/otlp

processors:
  batch:

  filter/logs:
    logs:
      log_record:
        - 'severity_number < 10'

  #  filter/error_spans:
  #    traces:
  #      span:
  #        - 'status.code == ERROR'
  filter/error_spans:
    traces:
      span:
        - 'status.code != 2'

#  filter/spans:
#    traces:
#      span:
#        - 'attributes["exception.message"] == nil'

  filter/test:
    traces:
      span:
        - 'attributes["exception.message"] == nil'

  attributes/spans:
    actions:
      - key: network.peer.address
        action: delete
      - key: server.address
        action: delete
      - key: client.address
        action: delete
      - key: network.protocol.version
        action: delete
      - key: network.peer.port
        action: delete
      - key: user_agent.original
        action: delete
      - key: url.scheme
        action: delete
      - key: thread.name
        action: delete

service:
  pipelines:
    logs/original:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/original_logs]

    logs/filtered:
      receivers: [otlp]
      processors: [batch, filter/logs]
      exporters: [file/filtered_logs]

    traces:
      receivers: [otlp]
      processors: [attributes/spans]
      exporters: [file/original_span]

    traces/error:
      receivers: [otlp]
      processors: [filter/error_spans, attributes/spans]
      exporters: [file/filtered_span]

    traces/test:
      receivers: [otlp]
      processors: [filter/error_spans, attributes/spans]
      exporters: [file/test]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics,prometheus]