server:
  port: 14040

spring:
  application:
    name: board-system
  datasource :
    url:  jdbc:postgresql://100.83.227.59:5532/rnp
    username : test_admin
    password : new1234!
    driver-class-name: org.postgresql.Driver
  jpa :
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always