server:
  port: 14040

spring:
  config:
    activate:
      on-profile: local
  application:
    name: board-system
  datasource:
    url: jdbc:postgresql://100.83.227.59:5532/rnp
    username: test_admin
    password: new1234!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

#  mail:
#    properties:
#      debug: false # default true
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

