spring:
  application:
    name: board-system
  datasource :
    url:  jdbc:h2:tcp:localhost/~/board-db
    username : ENC(arxVItng1k3ZMqFwkKrzv7uPiqj7Onf1x6Qc7F/v/WxDXA0zdnFBfIusN7IsuY29)
    password : ENC(+rn2lW7IwRW3EjEF500vPOEBYSmZzrX7IQUfxf7uUNpVtC/whiWE2koDwFir3EpH)
    driver-class-name : org.h2.Driver
  jpa :
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: false

server:
  port: 5050
jasypt:
  encryptor:
    bean: jasyptEncryptorAES

encrypt :
  key-file :
    path : C:\IntelliJProject\encrypt-key
